version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:665965545975:task-definition/ecs:2"
        LoadBalancerInfo:
          ContainerName: "devops"
          ContainerPort: 80
        PlatformVersion: "LATEST"
